const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

function createService(root = process.env.PACKSMITH_SERVER_DATA || path.join(process.cwd(), 'data')) {
  fs.mkdirSync(path.join(root, 'blobs'), { recursive: true });
  const db = new DatabaseSync(path.join(root, 'server.db'));
  const authSessions=new Map();const clientId=process.env.PACKSMITH_MS_CLIENT_ID||'60cbe4bd-6824-4be1-9685-7fd5c33fff61';const clientSecret=process.env.PACKSMITH_MS_CLIENT_SECRET;const redirectUri=process.env.PACKSMITH_MS_REDIRECT_URI||'https://auth.pack-smith.com/';
  db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS packs(code TEXT PRIMARY KEY, manifest TEXT NOT NULL, created_at INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS blobs(hash TEXT PRIMARY KEY, size INTEGER NOT NULL)');
  const reply=(res,status,value)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));};
  return http.createServer(async(req,res)=>{
    try {
      const url=new URL(req.url,'http://localhost');
      if(req.method==='GET'&&url.pathname==='/v1/auth/microsoft/start'){if(!clientSecret)return reply(res,503,{error:'Microsoft authentication is not configured on the server'});for(const[id,session]of authSessions)if(Date.now()-session.createdAt>10*60*1000)authSessions.delete(id);const sessionId=crypto.randomUUID();const verifier=crypto.randomBytes(32).toString('base64url');const challenge=crypto.createHash('sha256').update(verifier).digest('base64url');authSessions.set(sessionId,{verifier,createdAt:Date.now(),status:'pending'});const query=new URLSearchParams({client_id:clientId,response_type:'code',redirect_uri:redirectUri,response_mode:'query',scope:'XboxLive.signin offline_access',state:sessionId,code_challenge:challenge,code_challenge_method:'S256'});return reply(res,200,{sessionId,authorizationUrl:`https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize?${query}`});}
      if(req.method==='GET'&&url.pathname==='/'&&url.searchParams.has('state')){const sessionId=url.searchParams.get('state');const session=authSessions.get(sessionId);if(!session)return reply(res,400,{error:'Unknown or expired authentication session'});try{if(url.searchParams.get('error'))throw new Error(url.searchParams.get('error_description')||url.searchParams.get('error'));const body=new URLSearchParams({client_id:clientId,client_secret:clientSecret,grant_type:'authorization_code',code:url.searchParams.get('code'),redirect_uri:redirectUri,code_verifier:session.verifier});const tokenResponse=await fetch('https://login.microsoftonline.com/consumers/oauth2/v2.0/token',{method:'POST',body});const token=await tokenResponse.json();if(!tokenResponse.ok)throw new Error(token.error_description||token.error);authSessions.set(sessionId,{status:'complete',credentials:token,createdAt:session.createdAt});res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end('<!doctype html><title>Packsmith sign-in complete</title><h1>Signed in</h1><p>You can close this window and return to Packsmith.</p>');}catch(error){authSessions.set(sessionId,{status:'error',error:error.message,createdAt:session.createdAt});res.writeHead(400,{'content-type':'text/html; charset=utf-8'});return res.end('<!doctype html><title>Packsmith sign-in failed</title><h1>Sign-in failed</h1><p>Return to Packsmith for details.</p>');}}
      if(req.method==='GET'&&url.pathname==='/v1/auth/microsoft/result'){const sessionId=url.searchParams.get('session');const session=authSessions.get(sessionId);if(!session)return reply(res,404,{error:'Unknown or expired authentication session'});if(Date.now()-session.createdAt>10*60*1000){authSessions.delete(sessionId);return reply(res,410,{error:'Authentication session expired'});}if(session.status==='pending')return reply(res,202,{status:'pending'});authSessions.delete(sessionId);return session.status==='complete'?reply(res,200,{credentials:session.credentials}):reply(res,400,{error:session.error});}
      if(req.method==='GET' && req.url.startsWith('/v1/packs/')) { const code=req.url.split('/')[3]?.toUpperCase(); const row=db.prepare('SELECT manifest FROM packs WHERE code=?').get(code); return row?reply(res,200,JSON.parse(row.manifest)):reply(res,404,{error:'Pack not found'}); }
      if(req.method==='GET' && req.url.startsWith('/v1/blobs/')) { const hash=req.url.split('/')[3]; if(!/^[a-f0-9]{64}$/.test(hash))return reply(res,400,{error:'Invalid hash'});const file=path.join(root,'blobs',hash);if(!fs.existsSync(file))return reply(res,404,{error:'Blob not found'});res.writeHead(200,{'content-type':'application/java-archive','content-length':fs.statSync(file).size});return fs.createReadStream(file).pipe(res); }
      if(req.method==='POST' && req.url==='/v1/packs') { let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>256*1024*1024)throw new Error('Upload too large');chunks.push(chunk);}const input=JSON.parse(Buffer.concat(chunks));if(!input.name||!Array.isArray(input.files))return reply(res,400,{error:'name and files are required'});const files=input.files.map(file=>{const bytes=Buffer.from(file.data,'base64');const hash=crypto.createHash('sha256').update(bytes).digest('hex');const target=path.join(root,'blobs',hash);if(!fs.existsSync(target))fs.writeFileSync(target,bytes,{flag:'wx'});db.prepare('INSERT OR IGNORE INTO blobs(hash,size) VALUES(?,?)').run(hash,bytes.length);return {name:file.name,hash,size:bytes.length};});let code;do{code=`PS-${crypto.randomBytes(3).toString('hex').toUpperCase()}`;}while(db.prepare('SELECT 1 FROM packs WHERE code=?').get(code));const manifest={code,name:input.name,version:input.version||1,files};db.prepare('INSERT INTO packs VALUES(?,?,?)').run(code,JSON.stringify(manifest),Date.now());return reply(res,201,manifest); }
      reply(res,404,{error:'Not found'});
    } catch(error) { reply(res,error.message==='Upload too large'?413:400,{error:error.message}); }
  });
}
if(require.main===module)createService().listen(Number(process.env.PORT)||8787,()=>console.log(`Packsmith server listening on ${Number(process.env.PORT)||8787}`));
module.exports={createService};
